server.port: 8081
# This is a workaround for https://github.org/peimari/tab/as/main/layout/example/spring/issues/381
#spring.servlet.multipart.enabled: false


dockerDaemonMap:
  LOCAL_DD: "localhost"
  AWS_DD: ""

kafka.url: ${kafka}:9092


application:
  message: Hey there!
  appname: I'm theDarkCoderRises from DockerWorld.

elk.url: https://www.elastic.co/elk-stack

thresholdErrCnt: 5

x-axis: 5