server.port: 8081
# This is a workaround for https://github.org/peimari/tab/as/main/layout/example/spring/issues/381
#spring.servlet.multipart.enabled: false


dockerDaemonMap:
  LOCAL_DD: ${LOCAL:localhost}
  AWS_DD: ${AWS:}
#  OTHER_DD: ${OTHER_DD}

kafka.url: ${kafka}


application:
  message: Hey there!
  appname: I'm theDarkCoderRises from DockerWorld.

#elk.url: https://search-jbtdcresdomain-6ghjjpn3wxczrz4y2nsoucocue.ap-south-1.es.amazonaws.com/_plugin/kibana/app/kibana#/discover?_g=()&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'8f28b2b0-3f0b-11e9-b37c-1fb81f8331d8',key:'@log_stream',negate:!f,params:(query:'%s*',type:phrase),type:phrase,value:'%s*'),query:(match:('@log_stream':(query:'%s*',type:phrase))))),index:'8f28b2b0-3f0b-11e9-b37c-1fb81f8331d8',interval:auto,query:(language:lucene,query:''),sort:!(_score,desc))
elk.url: https://search-jbtdcresdomain-6ghjjpn3wxczrz4y2nsoucocue.ap-south-1.es.amazonaws.com//_plugin/kibana/app/kibana#/discover?_g=()&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'605e1a10-76ec-11e9-aca9-e9a1ca66640f',key:'@log_stream',negate:!f,params:(query:'%s*',type:phrase),type:phrase,value:'%s*'),query:(match:('@log_stream':(query:'%s*',type:phrase))))),index:'605e1a10-76ec-11e9-aca9-e9a1ca66640f',interval:auto,query:(language:lucene,query:''),sort:!(_score,desc))

thresholdErrCnt: 5
checkInterval: 30000

x-axis: 5

logging:
  level:
    root: ERROR
    org.springframework.web: INFO
    tdcr.notification: DEBUG
    org.apache.kafka: INFO
    com.amazonaws: INFO
  file: logs/curious.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file:
